import React from 'react'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Button } from '@/components/ui/button'
import { sessionDetail } from '../medical-agent/[sessionId]/page'
import Time from '@/utils/Time'

type Props = {
    record: sessionDetail,
}

export default function ViewReportDialog({record}:Props) {
    // console.log(record);
  return (
    <Dialog>
        <DialogTrigger asChild>
            <Button variant={'link'} size={'sm'}>View Report</Button>
        </DialogTrigger>
        <DialogContent className='max-w-[90vh] overflow-y-auto bg-white shadow-lg p-6 '>
            <DialogHeader>
            <DialogTitle> <h2 className='text-center text-2xl font-bold text-blue-500 mb-6'>Medical AI Voice Agent Report</h2> </DialogTitle>
            <DialogDescription>
                <div className='space-y-6 text-gray-800 text-sm '> 
                    <div>
                        <h3 className='text-xl font-semibold text-blue-500'>Session Info</h3>
                        <hr className="border-blue-500 border-t-3 rounded my-2" />
                        <div className='grid grid-cols-2'>
                            <h2 className='py-1 text-gray-400'> <span className='font-bold w-10'>Docter:</span> {record?.selectedDocter?.specialist}</h2>
                            <h2 className='py-1 text-gray-400'> <span className='font-bold w-10'>Consult Date:</span> {Time(record.createdOn)}</h2>
                            <h2 className='text-gray-400'> <span className='font-bold '>User:</span> {record?.selectedDocter?.specialist}</h2>
                            <h2 className='text-gray-400'> <span className='font-bold'>Agent:</span> {record?.selectedDocter?.specialist} AI</h2>   
                        </div>
                    </div>
                    <div>
                        <h3 className='text-xl font-semibold text-blue-500'>Chief Complaint</h3>
                        <hr className="border-blue-500 border-t-3 rounded my-2" />
                        <div className='grid grid-cols-2'>
                            <p>{record?.notes}</p>
                        </div>
                    </div>
                    <div>
                        <h3 className='text-xl font-semibold text-blue-500'>Summary</h3>
                        <hr className="border-blue-500 border-t-3 rounded my-2" />
                        <div className='grid grid-cols-2'>
                            <p>{record?.notes}</p>
                        </div>
                    </div>
                    <div>
                        <h3 className='text-xl font-semibold text-blue-500'>Symptoms</h3>
                         <hr className="border-blue-500 border-t-3 rounded my-2" />
                        <div className='grid grid-cols-2'>
                            <p>{record?.notes}</p>
                        </div>
                    </div>
                    <div>
                        <h3 className='text-xl font-semibold text-blue-500'>Duration & Severity</h3>
                         <hr className="border-blue-500 border-t-3 rounded my-2" />
                        <div className='grid grid-cols-2'>
                            <h2 className='py-1 text-gray-400'> <span className='font-bold w-10'>Durtion:</span> {record?.selectedDocter?.specialist}</h2>
                            <h2 className='py-1 text-gray-400'> <span className='font-bold w-10'>Severity:</span> {Time(record.createdOn)}</h2>
                        </div>
                    </div>
                    <hr className="border-t-2 rounded my-2" />
                    <p className='text-gray-400 text-center text-sm'>This report generated by an AI Medical Assistant for informational purposes only.</p>
                </div>
            </DialogDescription>
            </DialogHeader>
        </DialogContent>
    </Dialog>
  )
}
