import React from 'react'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Button } from '@/components/ui/button'
import { sessionDetail } from '../medical-agent/[sessionId]/page'
import Time from '@/utils/Time'

type Props = {
    record: sessionDetail,
}

export default function ViewReportDialog({record}:Props) {
  return (
    <Dialog>
    <DialogTrigger asChild>
        <Button variant="link" size="sm">View Report</Button>
    </DialogTrigger>

    <DialogContent className="max-w-[800px] h-[95vh] overflow-y-auto bg-white shadow-xl p-6">
        <DialogHeader>
        <DialogTitle>
            <h2 className="text-center text-3xl font-bold text-blue-600 mb-4">Medical Assistant Report</h2>
        </DialogTitle>

        <DialogDescription className="space-y-4 text-gray-700 text-base">
            <div>
            <h3 className="text-xl font-semibold text-blue-500">Session Info</h3>
            <hr className="border-blue-500 mt-1 mb-2" />
            <div className="grid grid-cols-2 gap-y-2">
                <p><span className="font-semibold">Doctor:</span> {record?.selectedDocter?.specialist}</p>
                <p><span className="font-semibold">Consult Date:</span> {Time(record.createdOn)}</p>
                <p><span className="font-semibold">User:</span> {record?.report?.user}</p>
                <p><span className="font-semibold">Agent:</span> {record?.report?.agent}</p>
            </div>
            </div>

            <div>
            <h3 className="text-xl font-semibold text-blue-500">Chief Complaint</h3>
            <hr className="border-blue-500 mt-1 mb-2" />
            <p className="leading-relaxed">{record?.report?.chiefComplaint}</p>
            </div>

            <div>
            <h3 className="text-xl font-semibold text-blue-500">Summary</h3>
            <hr className="border-blue-500 mt-1 mb-2" />
            <p className="leading-relaxed">{record?.report?.summary}</p>
            </div>

            <div>
            <h3 className="text-xl font-semibold text-blue-500">Symptoms</h3>
            <hr className="border-blue-500 mt-1 mb-2" />
            <ul className="list-disc list-inside space-y-1">
                {record?.report?.symptoms?.map((sym: string, i: number) => (
                <li key={i}>{sym}</li>
                ))}
            </ul>
            </div>

            <div>
            <h3 className="text-xl font-semibold text-blue-500">Duration & Severity</h3>
            <hr className="border-blue-500 mt-1 mb-2" />
            <div className="grid grid-cols-2 gap-y-2">
                <p><span className="font-semibold">Duration:</span> {record?.report?.duration}</p>
                <p><span className="font-semibold">Severity:</span> {record?.report?.severity}</p>
            </div>
            </div>

            {record?.report?.recommandations?.length > 0 && (
            <div>
                <h3 className="text-xl font-semibold text-blue-500">Recommendations</h3>
                <hr className="border-blue-500 mt-1 mb-2" />
                <ul className="list-disc list-inside space-y-1">
                {record?.report?.recommandations?.map((rec: string, i: number) => (
                    <li key={i}>{rec}</li>
                ))}
                </ul>
            </div>
            )}

            {record?.report?.medicationsMentioned?.length > 0 && (
            <div>
                <h3 className="text-xl font-semibold text-blue-500">Recommendations</h3>
                <hr className="border-blue-500 mt-1 mb-2" />
                <ul className="list-disc list-inside space-y-1">
                {record?.report?.medicationsMentioned?.map((rec: string, i: number) => (
                    <li key={i}>{rec}</li>
                ))}
                </ul>
            </div>
            )}

            <p className="text-gray-400 text-center text-sm">
            This report was generated by an AI Medical Assistant for informational purposes only.
            </p>
        </DialogDescription>
        </DialogHeader>
    </DialogContent>
    </Dialog>
  )
}
